
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file Book_Author.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Library.BLL.Validation;
#endregion

namespace Library.BLL
{
	///<summary>
	/// An object representation of the 'Book_Author' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class Book_AuthorBase : EntityBase, IBook_Author, IEntityId<Book_AuthorKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private Book_AuthorEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private Book_AuthorEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private Book_AuthorEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Book_Author> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event Book_AuthorEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event Book_AuthorEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="Book_AuthorBase"/> instance.
		///</summary>
		public Book_AuthorBase()
		{
			this.entityData = new Book_AuthorEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="Book_AuthorBase"/> instance.
		///</summary>
		///<param name="_book_ID"></param>
		///<param name="_author_ID"></param>
		public Book_AuthorBase(System.Int32 _book_ID, System.Int32 _author_ID)
		{
			this.entityData = new Book_AuthorEntityData();
			this.backupData = null;

			this.Book_ID = _book_ID;
			this.Author_ID = _author_ID;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Book_Author"/> instance.
		///</summary>
		///<param name="_book_ID"></param>
		///<param name="_author_ID"></param>
		public static Book_Author CreateBook_Author(System.Int32 _book_ID, System.Int32 _author_ID)
		{
			Book_Author newBook_Author = new Book_Author();
			newBook_Author.Book_ID = _book_ID;
			newBook_Author.Author_ID = _author_ID;
			return newBook_Author;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
				
                OnPropertyChanging("ID");                    
				OnColumnChanging(Book_AuthorColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(Book_AuthorColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Book_ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 Book_ID
		{
			get
			{
				return this.entityData.Book_ID; 
			}
			
			set
			{
				if (this.entityData.Book_ID == value)
					return;
				
                OnPropertyChanging("Book_ID");                    
				OnColumnChanging(Book_AuthorColumn.Book_ID, this.entityData.Book_ID);
				this.entityData.Book_ID = value;
				this.EntityId.Book_ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(Book_AuthorColumn.Book_ID, this.entityData.Book_ID);
				OnPropertyChanged("Book_ID");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Book_ID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Book_ID property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalBook_ID
		{
			get { return this.entityData.OriginalBook_ID; }
			set { this.entityData.OriginalBook_ID = value; }
		}
		
		/// <summary>
		/// 	Gets or sets the Author_ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, false, false)]
		public virtual System.Int32 Author_ID
		{
			get
			{
				return this.entityData.Author_ID; 
			}
			
			set
			{
				if (this.entityData.Author_ID == value)
					return;
				
                OnPropertyChanging("Author_ID");                    
				OnColumnChanging(Book_AuthorColumn.Author_ID, this.entityData.Author_ID);
				this.entityData.Author_ID = value;
				this.EntityId.Author_ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(Book_AuthorColumn.Author_ID, this.entityData.Author_ID);
				OnPropertyChanged("Author_ID");
			}
		}
		
		/// <summary>
		/// 	Get the original value of the Author_ID property.
		///		
		/// </summary>
		/// <remarks>This is the original value of the Author_ID property.</remarks>
		/// <value>This type is int</value>
		[BrowsableAttribute(false)/*, XmlIgnoreAttribute()*/]
		public  virtual System.Int32 OriginalAuthor_ID
		{
			get { return this.entityData.OriginalAuthor_ID; }
			set { this.entityData.OriginalAuthor_ID = value; }
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		/// <summary>
		/// Gets or sets the source <see cref="Author"/>.
		/// </summary>
		/// <value>The source Author for Author_ID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Author Author_IDSource
      	{
            get { return entityData.Author_IDSource; }
            set { entityData.Author_IDSource = value; }
      	}
		/// <summary>
		/// Gets or sets the source <see cref="Book"/>.
		/// </summary>
		/// <value>The source Book for Book_ID.</value>
        [XmlIgnore()]
		[Browsable(false), System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual Book Book_IDSource
      	{
            get { return entityData.Book_IDSource; }
            set { entityData.Book_IDSource = value; }
      	}
		#endregion
		
		#region Children Collections
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Book_Author"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "Book_ID", "Author_ID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as Book_AuthorEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Book_Author) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Book_Author>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Book_Author);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Book_Author Entity 
		///</summary>
		protected virtual Book_Author Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Book_Author copy = new Book_Author();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ID = this.ID;
				copy.Book_ID = this.Book_ID;
					copy.OriginalBook_ID = this.OriginalBook_ID;
				copy.Author_ID = this.Author_ID;
					copy.OriginalAuthor_ID = this.OriginalAuthor_ID;
			
			if (this.Author_IDSource != null && existingCopies.Contains(this.Author_IDSource))
				copy.Author_IDSource = existingCopies[this.Author_IDSource] as Author;
			else
				copy.Author_IDSource = MakeCopyOf(this.Author_IDSource, existingCopies) as Author;
			if (this.Book_IDSource != null && existingCopies.Contains(this.Book_IDSource))
				copy.Book_IDSource = existingCopies[this.Book_IDSource] as Book;
			else
				copy.Book_IDSource = MakeCopyOf(this.Book_IDSource, existingCopies) as Book;
		
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Book_Author Entity 
		///</summary>
		public virtual Book_Author Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Book_Author Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Book_Author DeepCopy()
		{
			return EntityHelper.Clone<Book_Author>(this as Book_Author);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as Book_AuthorEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new Book_AuthorEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as Book_AuthorEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(Book_AuthorColumn column)
		{
			switch(column)
			{
					case Book_AuthorColumn.ID:
					return entityData.ID != _originalData.ID;
					case Book_AuthorColumn.Book_ID:
					return entityData.Book_ID != _originalData.Book_ID;
					case Book_AuthorColumn.Author_ID:
					return entityData.Author_ID != _originalData.Author_ID;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< Book_AuthorColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.Book_ID != _originalData.Book_ID;
			result = result || entityData.Author_ID != _originalData.Author_ID;
			return result;
		}	
		
		///<summary>
		///  Returns a Book_Author Entity with the original data.
		///</summary>
		public Book_Author GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateBook_Author(
				_originalData.Book_ID,
				_originalData.Author_ID
				);
				
			return (Book_Author)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="Book_AuthorBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is Book_AuthorBase)
				return ValueEquals(this, (Book_AuthorBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="Book_AuthorBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ID.GetHashCode() ^ 
					this.Book_ID.GetHashCode() ^ 
					this.Author_ID.GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="Book_AuthorBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(Book_AuthorBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="Book_AuthorBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="Book_AuthorBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="Book_AuthorBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(Book_AuthorBase Object1, Book_AuthorBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ID != Object2.ID)
				equal = false;
			if (Object1.Book_ID != Object2.Book_ID)
				equal = false;
			if (Object1.Author_ID != Object2.Author_ID)
				equal = false;
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((Book_AuthorBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static Book_AuthorComparer GetComparer()
        {
            return new Book_AuthorComparer();
        }
        */

        // Comparer delegates back to Book_Author
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Book_Author rhs, Book_AuthorColumn which)
        {
            switch (which)
            {
            	
            	
            	case Book_AuthorColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case Book_AuthorColumn.Book_ID:
            		return this.Book_ID.CompareTo(rhs.Book_ID);
            		
            		                 
            	
            	
            	case Book_AuthorColumn.Author_ID:
            		return this.Author_ID.CompareTo(rhs.Author_ID);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<Book_AuthorKey> Members
		
		// member variable for the EntityId property
		private Book_AuthorKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual Book_AuthorKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new Book_AuthorKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Book_Author")
					.Append("|").Append( this.Book_ID.ToString())
					.Append("|").Append( this.Author_ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{4}{3}- ID: {0}{3}- Book_ID: {1}{3}- Author_ID: {2}{3}{5}", 
				this.ID,
				this.Book_ID,
				this.Author_ID,
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Book_Author' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class Book_AuthorEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// Book_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Book_Author"</remarks>
		public System.Int32 Book_ID;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalBook_ID;
		
		/// <summary>			
		/// Author_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Book_Author"</remarks>
		public System.Int32 Author_ID;
			
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		public System.Int32 OriginalAuthor_ID;
		
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// ID : 
		/// </summary>
		public System.Int32 ID = (int)0;
		#endregion
			
		#region Source Foreign Key Property
				
		private Author _author_IDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Author"/>.
		/// </summary>
		/// <value>The source Author for Author_ID.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Author Author_IDSource
      	{
            get { return this._author_IDSource; }
            set { this._author_IDSource = value; }
      	}
		private Book _book_IDSource = null;
		
		/// <summary>
		/// Gets or sets the source <see cref="Book"/>.
		/// </summary>
		/// <value>The source Book for Book_ID.</value>
		[XmlIgnore()]
		[Browsable(false)]
		public virtual Book Book_IDSource
      	{
            get { return this._book_IDSource; }
            set { this._book_IDSource = value; }
      	}
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			Book_AuthorEntityData _tmp = new Book_AuthorEntityData();
						
			_tmp.Book_ID = this.Book_ID;
			_tmp.OriginalBook_ID = this.OriginalBook_ID;
			_tmp.Author_ID = this.Author_ID;
			_tmp.OriginalAuthor_ID = this.OriginalAuthor_ID;
			
			_tmp.ID = this.ID;
			
			#region Source Parent Composite Entities
			if (this.Author_IDSource != null)
				_tmp.Author_IDSource = MakeCopyOf(this.Author_IDSource) as Author;
			if (this.Book_IDSource != null)
				_tmp.Book_IDSource = MakeCopyOf(this.Book_IDSource) as Book;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			Book_AuthorEntityData _tmp = new Book_AuthorEntityData();
						
			_tmp.Book_ID = this.Book_ID;
			_tmp.OriginalBook_ID = this.OriginalBook_ID;
			_tmp.Author_ID = this.Author_ID;
			_tmp.OriginalAuthor_ID = this.OriginalAuthor_ID;
			
			_tmp.ID = this.ID;
			
			#region Source Parent Composite Entities
			if (this.Author_IDSource != null && existingCopies.Contains(this.Author_IDSource))
				_tmp.Author_IDSource = existingCopies[this.Author_IDSource] as Author;
			else
				_tmp.Author_IDSource = MakeCopyOf(this.Author_IDSource, existingCopies) as Author;
			if (this.Book_IDSource != null && existingCopies.Contains(this.Book_IDSource))
				_tmp.Book_IDSource = existingCopies[this.Book_IDSource] as Book;
			else
				_tmp.Book_IDSource = MakeCopyOf(this.Book_IDSource, existingCopies) as Book;
			#endregion
		
			#region Child Collections
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="Book_AuthorColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(Book_AuthorColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="Book_AuthorColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(Book_AuthorColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="Book_AuthorColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(Book_AuthorColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				Book_AuthorEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new Book_AuthorEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="Book_AuthorColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(Book_AuthorColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				Book_AuthorEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new Book_AuthorEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region Book_AuthorEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Book_Author"/> object.
	/// </remarks>
	public class Book_AuthorEventArgs : System.EventArgs
	{
		private Book_AuthorColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the Book_AuthorEventArgs class.
		///</summary>
		public Book_AuthorEventArgs(Book_AuthorColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the Book_AuthorEventArgs class.
		///</summary>
		public Book_AuthorEventArgs(Book_AuthorColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The Book_AuthorColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="Book_AuthorColumn" />
		public Book_AuthorColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Book_Author related events.
	///</summary>
	public delegate void Book_AuthorEventHandler(object sender, Book_AuthorEventArgs e);
	
	#region Book_AuthorComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class Book_AuthorComparer : System.Collections.Generic.IComparer<Book_Author>
	{
		Book_AuthorColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:Book_AuthorComparer"/> class.
        /// </summary>
		public Book_AuthorComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:Book_AuthorComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public Book_AuthorComparer(Book_AuthorColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Book_Author"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Book_Author"/> to compare.</param>
        /// <param name="b">The second <c>Book_Author</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Book_Author a, Book_Author b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Book_Author entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Book_Author a, Book_Author b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public Book_AuthorColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region Book_AuthorKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Book_Author"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class Book_AuthorKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the Book_AuthorKey class.
		/// </summary>
		public Book_AuthorKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the Book_AuthorKey class.
		/// </summary>
		public Book_AuthorKey(Book_AuthorBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.Book_ID = entity.Book_ID;
				this.Author_ID = entity.Author_ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the Book_AuthorKey class.
		/// </summary>
		public Book_AuthorKey(System.Int32 _book_ID, System.Int32 _author_ID)
		{
			#region Init Properties

			this.Book_ID = _book_ID;
			this.Author_ID = _author_ID;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private Book_AuthorBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public Book_AuthorBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the Book_ID property
		private System.Int32 _book_ID;
		
		/// <summary>
		/// Gets or sets the Book_ID property.
		/// </summary>
		public System.Int32 Book_ID
		{
			get { return _book_ID; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Book_ID = value;
				
				_book_ID = value;
			}
		}
		
		// member variable for the Author_ID property
		private System.Int32 _author_ID;
		
		/// <summary>
		/// Gets or sets the Author_ID property.
		/// </summary>
		public System.Int32 Author_ID
		{
			get { return _author_ID; }
			set
			{
				if ( this.Entity != null )
					this.Entity.Author_ID = value;
				
				_author_ID = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				Book_ID = ( values["Book_ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Book_ID"], typeof(System.Int32)) : (int)0;
				Author_ID = ( values["Author_ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["Author_ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("Book_ID", Book_ID);
			values.Add("Author_ID", Author_ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("Book_ID: {0}{2}Author_ID: {1}{2}",
								Book_ID,
								Author_ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region Book_AuthorColumn Enum
	
	/// <summary>
	/// Enumerate the Book_Author columns.
	/// </summary>
	[Serializable]
	public enum Book_AuthorColumn : int
	{
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, false, true, false)]
		ID = 1,
		/// <summary>
		/// Book_ID : 
		/// </summary>
		[EnumTextValue("BookID")]
		[ColumnEnum("Book_ID", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		Book_ID = 2,
		/// <summary>
		/// Author_ID : 
		/// </summary>
		[EnumTextValue("AuthorID")]
		[ColumnEnum("Author_ID", typeof(System.Int32), System.Data.DbType.Int32, true, false, false)]
		Author_ID = 3
	}//End enum

	#endregion Book_AuthorColumn Enum

} // end namespace
