using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Author' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IAuthor 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Author"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		System.String  Name  { get; set; }
		
		/// <summary>
		/// Country : 
		/// </summary>
		System.String  Country  { get; set; }
		
		/// <summary>
		/// City : 
		/// </summary>
		System.String  City  { get; set; }
		
		/// <summary>
		/// BirthDate : 
		/// </summary>
		System.DateTime?  BirthDate  { get; set; }
		
		/// <summary>
		/// Position : 
		/// </summary>
		System.String  Position  { get; set; }
		
		/// <summary>
		/// IsAlive : 
		/// </summary>
		System.String  IsAlive  { get; set; }
		
		/// <summary>
		/// Mobile : 
		/// </summary>
		System.String  Mobile  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Website : 
		/// </summary>
		System.String  Website  { get; set; }
		
		/// <summary>
		/// Gender : 
		/// </summary>
		System.Boolean?  Gender  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table book_IDBookCollection_From_Book_Author
		/// </summary>	
		TList<Book> Book_IDBookCollection_From_Book_Author { get; set; }	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _book_AuthorAuthor_ID
		/// </summary>	
		TList<Book_Author> Book_AuthorCollection {  get;  set;}	

		#endregion Data Properties

	}
}


