using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Book_Author' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBook_Author 
	{
		/// <summary>			
		/// Book_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Book_Author"</remarks>
		System.Int32 Book_ID { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalBook_ID { get; set; }
			
		/// <summary>			
		/// Author_ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Book_Author"</remarks>
		System.Int32 Author_ID { get; set; }
				
		/// <summary>
		/// keep a copy of the original so it can be used for editable primary keys.
		/// </summary>
		System.Int32 OriginalAuthor_ID { get; set; }
			
		
		
		/// <summary>
		/// ID : 
		/// </summary>
		System.Int32  ID  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


