using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Book' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IBook 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Book"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		System.String  Name  { get; set; }
		
		/// <summary>
		/// Publisher : 
		/// </summary>
		System.String  Publisher  { get; set; }
		
		/// <summary>
		/// Publish_Date : 
		/// </summary>
		System.DateTime?  Publish_Date  { get; set; }
		
		/// <summary>
		/// IsAvailablePdf : 
		/// </summary>
		System.Boolean?  IsAvailablePdf  { get; set; }
		
		/// <summary>
		/// IsAvailablePaper : 
		/// </summary>
		System.Boolean?  IsAvailablePaper  { get; set; }
		
		/// <summary>
		/// IsBorrowed : 
		/// </summary>
		System.Boolean  IsBorrowed  { get; set; }
		
		/// <summary>
		/// User_ID : 
		/// </summary>
		System.Int32  User_ID  { get; set; }
		
		/// <summary>
		/// BorrowDate : 
		/// </summary>
		System.DateTime?  BorrowDate  { get; set; }
		
		/// <summary>
		/// Borrow_Times : 
		/// </summary>
		System.Int32?  Borrow_Times  { get; set; }
		
		/// <summary>
		/// IsLost : 
		/// </summary>
		System.Boolean?  IsLost  { get; set; }
		
		/// <summary>
		/// Type_ID : 
		/// </summary>
		System.Int32  Type_ID  { get; set; }
		
		/// <summary>
		/// Publisher_ID : 
		/// </summary>
		System.Int32  Publisher_ID  { get; set; }
		
		/// <summary>
		/// Papers_no : 
		/// </summary>
		System.Int32?  Papers_no  { get; set; }
		
		/// <summary>
		/// Introducer_ID : 
		/// </summary>
		System.Int32?  Introducer_ID  { get; set; }
		
		/// <summary>
		/// EmployeeI_D : 
		/// </summary>
		System.Int32  EmployeeI_D  { get; set; }
		
		/// <summary>
		/// Size : 
		/// </summary>
		System.Double?  Size  { get; set; }
		
		/// <summary>
		/// Price : 
		/// </summary>
		System.Int32?  Price  { get; set; }
		
		/// <summary>
		/// Pdf_Link : 
		/// </summary>
		System.String  Pdf_Link  { get; set; }
		
		/// <summary>
		/// Image_ID : 
		/// </summary>
		System.Int32  Image_ID  { get; set; }
		
		/// <summary>
		/// ISBN : 
		/// </summary>
		System.String  ISBN  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
		
		/// <summary>
		/// CreatedBy : 
		/// </summary>
		System.Int32?  CreatedBy  { get; set; }
		
		/// <summary>
		/// UpdatedOn : 
		/// </summary>
		System.DateTime?  UpdatedOn  { get; set; }
		
		/// <summary>
		/// UpdatedBy : 
		/// </summary>
		System.Int32?  UpdatedBy  { get; set; }
		
		/// <summary>
		/// DeletedOn : 
		/// </summary>
		System.DateTime?  DeletedOn  { get; set; }
		
		/// <summary>
		/// DeletedBy : 
		/// </summary>
		System.Int32?  DeletedBy  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the junction table author_IDAuthorCollection_From_Book_Author
		/// </summary>	
		TList<Author> Author_IDAuthorCollection_From_Book_Author { get; set; }	


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _book_AuthorBook_ID
		/// </summary>	
		TList<Book_Author> Book_AuthorCollection {  get;  set;}	

		#endregion Data Properties

	}
}


