using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Course' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface ICourse 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Course"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Course_Name : 
		/// </summary>
		System.String  Course_Name  { get; set; }
		
		/// <summary>
		/// Course_Scope : 
		/// </summary>
		System.Int32  Course_Scope  { get; set; }
		
		/// <summary>
		/// Duration : 
		/// </summary>
		System.Int32  Duration  { get; set; }
		
		/// <summary>
		/// DurationType_ID : 
		/// </summary>
		System.Int32  DurationType_ID  { get; set; }
		
		/// <summary>
		/// Is_Deleted : 
		/// </summary>
		System.Boolean?  Is_Deleted  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
		
		/// <summary>
		/// CreatedBy : 
		/// </summary>
		System.Int32?  CreatedBy  { get; set; }
		
		/// <summary>
		/// UpdatedOn : 
		/// </summary>
		System.DateTime?  UpdatedOn  { get; set; }
		
		/// <summary>
		/// UpdatedBy : 
		/// </summary>
		System.Int32?  UpdatedBy  { get; set; }
		
		/// <summary>
		/// DeletedOn : 
		/// </summary>
		System.DateTime?  DeletedOn  { get; set; }
		
		/// <summary>
		/// DeletedBy : 
		/// </summary>
		System.Int32?  DeletedBy  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties

		#endregion Data Properties

	}
}


