using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Employee' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IEmployee 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Employee"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// UserName : 
		/// </summary>
		System.String  UserName  { get; set; }
		
		/// <summary>
		/// Password : 
		/// </summary>
		System.String  Password  { get; set; }
		
		/// <summary>
		/// Last_Login : 
		/// </summary>
		System.DateTime?  Last_Login  { get; set; }
		
		/// <summary>
		/// Last_Logout : 
		/// </summary>
		System.DateTime  Last_Logout  { get; set; }
		
		/// <summary>
		/// Is_Online : 
		/// </summary>
		System.Boolean?  Is_Online  { get; set; }
		
		/// <summary>
		/// Is_Active : 
		/// </summary>
		System.Boolean?  Is_Active  { get; set; }
		
		/// <summary>
		/// Is_Admin : 
		/// </summary>
		System.Boolean?  Is_Admin  { get; set; }
		
		/// <summary>
		/// First_Name : 
		/// </summary>
		System.String  First_Name  { get; set; }
		
		/// <summary>
		/// Last_Name : 
		/// </summary>
		System.String  Last_Name  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Country : 
		/// </summary>
		System.String  Country  { get; set; }
		
		/// <summary>
		/// City : 
		/// </summary>
		System.String  City  { get; set; }
		
		/// <summary>
		/// Address : 
		/// </summary>
		System.String  Address  { get; set; }
		
		/// <summary>
		/// Mobile : 
		/// </summary>
		System.String  Mobile  { get; set; }
		
		/// <summary>
		/// Phone : 
		/// </summary>
		System.String  Phone  { get; set; }
		
		/// <summary>
		/// Postion : 
		/// </summary>
		System.String  Postion  { get; set; }
		
		/// <summary>
		/// Is_Deleted : 
		/// </summary>
		System.Boolean?  Is_Deleted  { get; set; }
		
		/// <summary>
		/// CreatedOn : 
		/// </summary>
		System.DateTime?  CreatedOn  { get; set; }
		
		/// <summary>
		/// CreatedBy : 
		/// </summary>
		System.Int32?  CreatedBy  { get; set; }
		
		/// <summary>
		/// UpdatedOn : 
		/// </summary>
		System.DateTime?  UpdatedOn  { get; set; }
		
		/// <summary>
		/// UpdatedBy : 
		/// </summary>
		System.Int32?  UpdatedBy  { get; set; }
		
		/// <summary>
		/// DeletedOn : 
		/// </summary>
		System.DateTime?  DeletedOn  { get; set; }
		
		/// <summary>
		/// DeletedBy : 
		/// </summary>
		System.Int32?  DeletedBy  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bookEmployeeI_D
		/// </summary>	
		TList<Book> BookCollection {  get;  set;}	

		#endregion Data Properties

	}
}


