
/*
	File generated by NetTiers templates [www.nettiers.net]
	Important: Do not modify this file. Edit the file Introducer.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Library.BLL.Validation;
#endregion

namespace Library.BLL
{
	///<summary>
	/// An object representation of the 'Introducer' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class IntroducerBase : EntityBase, IIntroducer, IEntityId<IntroducerKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private IntroducerEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private IntroducerEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private IntroducerEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Introducer> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event IntroducerEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event IntroducerEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="IntroducerBase"/> instance.
		///</summary>
		public IntroducerBase()
		{
			this.entityData = new IntroducerEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="IntroducerBase"/> instance.
		///</summary>
		///<param name="_name"></param>
		///<param name="_country"></param>
		///<param name="_city"></param>
		///<param name="_birthDate"></param>
		///<param name="_position"></param>
		///<param name="_isAlive"></param>
		///<param name="_mobile"></param>
		///<param name="_email"></param>
		///<param name="_website"></param>
		///<param name="_book_ID"></param>
		///<param name="_gender"></param>
		public IntroducerBase(System.String _name, System.String _country, System.String _city, 
			System.DateTime? _birthDate, System.String _position, System.String _isAlive, System.String _mobile, 
			System.String _email, System.String _website, System.Int32 _book_ID, System.Boolean? _gender)
		{
			this.entityData = new IntroducerEntityData();
			this.backupData = null;

			this.Name = _name;
			this.Country = _country;
			this.City = _city;
			this.BirthDate = _birthDate;
			this.Position = _position;
			this.IsAlive = _isAlive;
			this.Mobile = _mobile;
			this.Email = _email;
			this.Website = _website;
			this.Book_ID = _book_ID;
			this.Gender = _gender;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Introducer"/> instance.
		///</summary>
		///<param name="_name"></param>
		///<param name="_country"></param>
		///<param name="_city"></param>
		///<param name="_birthDate"></param>
		///<param name="_position"></param>
		///<param name="_isAlive"></param>
		///<param name="_mobile"></param>
		///<param name="_email"></param>
		///<param name="_website"></param>
		///<param name="_book_ID"></param>
		///<param name="_gender"></param>
		public static Introducer CreateIntroducer(System.String _name, System.String _country, System.String _city, 
			System.DateTime? _birthDate, System.String _position, System.String _isAlive, System.String _mobile, 
			System.String _email, System.String _website, System.Int32 _book_ID, System.Boolean? _gender)
		{
			Introducer newIntroducer = new Introducer();
			newIntroducer.Name = _name;
			newIntroducer.Country = _country;
			newIntroducer.City = _city;
			newIntroducer.BirthDate = _birthDate;
			newIntroducer.Position = _position;
			newIntroducer.IsAlive = _isAlive;
			newIntroducer.Mobile = _mobile;
			newIntroducer.Email = _email;
			newIntroducer.Website = _website;
			newIntroducer.Book_ID = _book_ID;
			newIntroducer.Gender = _gender;
			return newIntroducer;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public override System.Int32 ID
		{
			get
			{
				return this.entityData.ID; 
			}
			
			set
			{
				if (this.entityData.ID == value)
					return;
				
                OnPropertyChanging("ID");                    
				OnColumnChanging(IntroducerColumn.ID, this.entityData.ID);
				this.entityData.ID = value;
				this.EntityId.ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.ID, this.entityData.ID);
				OnPropertyChanged("ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Name property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		/// <exception cref="ArgumentNullException">If you attempt to set to null.</exception>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false, 50)]
		public virtual System.String Name
		{
			get
			{
				return this.entityData.Name; 
			}
			
			set
			{
				if (this.entityData.Name == value)
					return;
				
                OnPropertyChanging("Name");                    
				OnColumnChanging(IntroducerColumn.Name, this.entityData.Name);
				this.entityData.Name = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Name, this.entityData.Name);
				OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Country property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Country
		{
			get
			{
				return this.entityData.Country; 
			}
			
			set
			{
				if (this.entityData.Country == value)
					return;
				
                OnPropertyChanging("Country");                    
				OnColumnChanging(IntroducerColumn.Country, this.entityData.Country);
				this.entityData.Country = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Country, this.entityData.Country);
				OnPropertyChanged("Country");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the City property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String City
		{
			get
			{
				return this.entityData.City; 
			}
			
			set
			{
				if (this.entityData.City == value)
					return;
				
                OnPropertyChanging("City");                    
				OnColumnChanging(IntroducerColumn.City, this.entityData.City);
				this.entityData.City = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.City, this.entityData.City);
				OnPropertyChanged("City");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the BirthDate property. 
		///		
		/// </summary>
		/// <value>This type is date.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? BirthDate
		{
			get
			{
				return this.entityData.BirthDate; 
			}
			
			set
			{
				if (this.entityData.BirthDate == value)
					return;
				
                OnPropertyChanging("BirthDate");                    
				OnColumnChanging(IntroducerColumn.BirthDate, this.entityData.BirthDate);
				this.entityData.BirthDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.BirthDate, this.entityData.BirthDate);
				OnPropertyChanged("BirthDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Position property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Position
		{
			get
			{
				return this.entityData.Position; 
			}
			
			set
			{
				if (this.entityData.Position == value)
					return;
				
                OnPropertyChanging("Position");                    
				OnColumnChanging(IntroducerColumn.Position, this.entityData.Position);
				this.entityData.Position = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Position, this.entityData.Position);
				OnPropertyChanged("Position");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsAlive property. 
		///		
		/// </summary>
		/// <value>This type is nchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String IsAlive
		{
			get
			{
				return this.entityData.IsAlive; 
			}
			
			set
			{
				if (this.entityData.IsAlive == value)
					return;
				
                OnPropertyChanging("IsAlive");                    
				OnColumnChanging(IntroducerColumn.IsAlive, this.entityData.IsAlive);
				this.entityData.IsAlive = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.IsAlive, this.entityData.IsAlive);
				OnPropertyChanged("IsAlive");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Mobile property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Mobile
		{
			get
			{
				return this.entityData.Mobile; 
			}
			
			set
			{
				if (this.entityData.Mobile == value)
					return;
				
                OnPropertyChanging("Mobile");                    
				OnColumnChanging(IntroducerColumn.Mobile, this.entityData.Mobile);
				this.entityData.Mobile = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Mobile, this.entityData.Mobile);
				OnPropertyChanged("Mobile");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Email property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Email
		{
			get
			{
				return this.entityData.Email; 
			}
			
			set
			{
				if (this.entityData.Email == value)
					return;
				
                OnPropertyChanging("Email");                    
				OnColumnChanging(IntroducerColumn.Email, this.entityData.Email);
				this.entityData.Email = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Email, this.entityData.Email);
				OnPropertyChanged("Email");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Website property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 50)]
		public virtual System.String Website
		{
			get
			{
				return this.entityData.Website; 
			}
			
			set
			{
				if (this.entityData.Website == value)
					return;
				
                OnPropertyChanging("Website");                    
				OnColumnChanging(IntroducerColumn.Website, this.entityData.Website);
				this.entityData.Website = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Website, this.entityData.Website);
				OnPropertyChanged("Website");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Book_ID property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.Int32 Book_ID
		{
			get
			{
				return this.entityData.Book_ID; 
			}
			
			set
			{
				if (this.entityData.Book_ID == value)
					return;
				
                OnPropertyChanging("Book_ID");                    
				OnColumnChanging(IntroducerColumn.Book_ID, this.entityData.Book_ID);
				this.entityData.Book_ID = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Book_ID, this.entityData.Book_ID);
				OnPropertyChanged("Book_ID");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Gender property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null it is up to the developer to check using the HasValue property
		/// and perform business logic appropriately.
		/// </remarks>
		
		




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Gender
		{
			get
			{
				return this.entityData.Gender; 
			}
			
			set
			{
				if (this.entityData.Gender == value)
					return;
				
                OnPropertyChanging("Gender");                    
				OnColumnChanging(IntroducerColumn.Gender, this.entityData.Gender);
				this.entityData.Gender = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(IntroducerColumn.Gender, this.entityData.Gender);
				OnPropertyChanged("Gender");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of Book objects
		///	which are related to this object through the relation FK_Book_Introducer
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<Book> BookCollection
		{
			get { return entityData.BookCollection; }
			set { entityData.BookCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.NotNull,
				new ValidationRuleArgs("Name", "Name"));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Name", "Name", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Country", "Country", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("City", "City", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Position", "Position", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("IsAlive", "Is Alive", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Mobile", "Mobile", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Email", "Email", 50));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Website", "Website", 50));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "Introducer"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ID", "Name", "Country", "City", "BirthDate", "Position", "IsAlive", "Mobile", "Email", "Website", "Book_ID", "Gender"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as IntroducerEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Introducer) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Introducer>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Introducer);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Introducer Entity 
		///</summary>
		protected virtual Introducer Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Introducer copy = new Introducer();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ID = this.ID;
				copy.Name = this.Name;
				copy.Country = this.Country;
				copy.City = this.City;
				copy.BirthDate = this.BirthDate;
				copy.Position = this.Position;
				copy.IsAlive = this.IsAlive;
				copy.Mobile = this.Mobile;
				copy.Email = this.Email;
				copy.Website = this.Website;
				copy.Book_ID = this.Book_ID;
				copy.Gender = this.Gender;
			
		
			//deep copy nested objects
			copy.BookCollection = (TList<Book>) MakeCopyOf(this.BookCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Introducer Entity 
		///</summary>
		public virtual Introducer Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Introducer Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Introducer DeepCopy()
		{
			return EntityHelper.Clone<Introducer>(this as Introducer);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as IntroducerEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new IntroducerEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as IntroducerEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(IntroducerColumn column)
		{
			switch(column)
			{
					case IntroducerColumn.ID:
					return entityData.ID != _originalData.ID;
					case IntroducerColumn.Name:
					return entityData.Name != _originalData.Name;
					case IntroducerColumn.Country:
					return entityData.Country != _originalData.Country;
					case IntroducerColumn.City:
					return entityData.City != _originalData.City;
					case IntroducerColumn.BirthDate:
					return entityData.BirthDate != _originalData.BirthDate;
					case IntroducerColumn.Position:
					return entityData.Position != _originalData.Position;
					case IntroducerColumn.IsAlive:
					return entityData.IsAlive != _originalData.IsAlive;
					case IntroducerColumn.Mobile:
					return entityData.Mobile != _originalData.Mobile;
					case IntroducerColumn.Email:
					return entityData.Email != _originalData.Email;
					case IntroducerColumn.Website:
					return entityData.Website != _originalData.Website;
					case IntroducerColumn.Book_ID:
					return entityData.Book_ID != _originalData.Book_ID;
					case IntroducerColumn.Gender:
					return entityData.Gender != _originalData.Gender;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< IntroducerColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ID != _originalData.ID;
			result = result || entityData.Name != _originalData.Name;
			result = result || entityData.Country != _originalData.Country;
			result = result || entityData.City != _originalData.City;
			result = result || entityData.BirthDate != _originalData.BirthDate;
			result = result || entityData.Position != _originalData.Position;
			result = result || entityData.IsAlive != _originalData.IsAlive;
			result = result || entityData.Mobile != _originalData.Mobile;
			result = result || entityData.Email != _originalData.Email;
			result = result || entityData.Website != _originalData.Website;
			result = result || entityData.Book_ID != _originalData.Book_ID;
			result = result || entityData.Gender != _originalData.Gender;
			return result;
		}	
		
		///<summary>
		///  Returns a Introducer Entity with the original data.
		///</summary>
		public Introducer GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateIntroducer(
				_originalData.Name,
				_originalData.Country,
				_originalData.City,
				_originalData.BirthDate,
				_originalData.Position,
				_originalData.IsAlive,
				_originalData.Mobile,
				_originalData.Email,
				_originalData.Website,
				_originalData.Book_ID,
				_originalData.Gender
				);
				
			return (Introducer)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="IntroducerBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is IntroducerBase)
				return ValueEquals(this, (IntroducerBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="IntroducerBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ID.GetHashCode() ^ 
					this.Name.GetHashCode() ^ 
					((this.Country == null) ? string.Empty : this.Country.ToString()).GetHashCode() ^ 
					((this.City == null) ? string.Empty : this.City.ToString()).GetHashCode() ^ 
					((this.BirthDate == null) ? string.Empty : this.BirthDate.ToString()).GetHashCode() ^ 
					((this.Position == null) ? string.Empty : this.Position.ToString()).GetHashCode() ^ 
					((this.IsAlive == null) ? string.Empty : this.IsAlive.ToString()).GetHashCode() ^ 
					((this.Mobile == null) ? string.Empty : this.Mobile.ToString()).GetHashCode() ^ 
					((this.Email == null) ? string.Empty : this.Email.ToString()).GetHashCode() ^ 
					((this.Website == null) ? string.Empty : this.Website.ToString()).GetHashCode() ^ 
					this.Book_ID.GetHashCode() ^ 
					((this.Gender == null) ? string.Empty : this.Gender.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="IntroducerBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(IntroducerBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="IntroducerBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="IntroducerBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="IntroducerBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(IntroducerBase Object1, IntroducerBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ID != Object2.ID)
				equal = false;
			if (Object1.Name != Object2.Name)
				equal = false;
			if ( Object1.Country != null && Object2.Country != null )
			{
				if (Object1.Country != Object2.Country)
					equal = false;
			}
			else if (Object1.Country == null ^ Object2.Country == null )
			{
				equal = false;
			}
			if ( Object1.City != null && Object2.City != null )
			{
				if (Object1.City != Object2.City)
					equal = false;
			}
			else if (Object1.City == null ^ Object2.City == null )
			{
				equal = false;
			}
			if ( Object1.BirthDate != null && Object2.BirthDate != null )
			{
				if (Object1.BirthDate != Object2.BirthDate)
					equal = false;
			}
			else if (Object1.BirthDate == null ^ Object2.BirthDate == null )
			{
				equal = false;
			}
			if ( Object1.Position != null && Object2.Position != null )
			{
				if (Object1.Position != Object2.Position)
					equal = false;
			}
			else if (Object1.Position == null ^ Object2.Position == null )
			{
				equal = false;
			}
			if ( Object1.IsAlive != null && Object2.IsAlive != null )
			{
				if (Object1.IsAlive != Object2.IsAlive)
					equal = false;
			}
			else if (Object1.IsAlive == null ^ Object2.IsAlive == null )
			{
				equal = false;
			}
			if ( Object1.Mobile != null && Object2.Mobile != null )
			{
				if (Object1.Mobile != Object2.Mobile)
					equal = false;
			}
			else if (Object1.Mobile == null ^ Object2.Mobile == null )
			{
				equal = false;
			}
			if ( Object1.Email != null && Object2.Email != null )
			{
				if (Object1.Email != Object2.Email)
					equal = false;
			}
			else if (Object1.Email == null ^ Object2.Email == null )
			{
				equal = false;
			}
			if ( Object1.Website != null && Object2.Website != null )
			{
				if (Object1.Website != Object2.Website)
					equal = false;
			}
			else if (Object1.Website == null ^ Object2.Website == null )
			{
				equal = false;
			}
			if (Object1.Book_ID != Object2.Book_ID)
				equal = false;
			if ( Object1.Gender != null && Object2.Gender != null )
			{
				if (Object1.Gender != Object2.Gender)
					equal = false;
			}
			else if (Object1.Gender == null ^ Object2.Gender == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((IntroducerBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static IntroducerComparer GetComparer()
        {
            return new IntroducerComparer();
        }
        */

        // Comparer delegates back to Introducer
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Introducer rhs, IntroducerColumn which)
        {
            switch (which)
            {
            	
            	
            	case IntroducerColumn.ID:
            		return this.ID.CompareTo(rhs.ID);
            		
            		                 
            	
            	
            	case IntroducerColumn.Name:
            		return this.Name.CompareTo(rhs.Name);
            		
            		                 
            	
            	
            	case IntroducerColumn.Country:
            		return this.Country.CompareTo(rhs.Country);
            		
            		                 
            	
            	
            	case IntroducerColumn.City:
            		return this.City.CompareTo(rhs.City);
            		
            		                 
            	
            	
            	case IntroducerColumn.BirthDate:
            		return this.BirthDate.Value.CompareTo(rhs.BirthDate.Value);
            		
            		                 
            	
            	
            	case IntroducerColumn.Position:
            		return this.Position.CompareTo(rhs.Position);
            		
            		                 
            	
            	
            	case IntroducerColumn.IsAlive:
            		return this.IsAlive.CompareTo(rhs.IsAlive);
            		
            		                 
            	
            	
            	case IntroducerColumn.Mobile:
            		return this.Mobile.CompareTo(rhs.Mobile);
            		
            		                 
            	
            	
            	case IntroducerColumn.Email:
            		return this.Email.CompareTo(rhs.Email);
            		
            		                 
            	
            	
            	case IntroducerColumn.Website:
            		return this.Website.CompareTo(rhs.Website);
            		
            		                 
            	
            	
            	case IntroducerColumn.Book_ID:
            		return this.Book_ID.CompareTo(rhs.Book_ID);
            		
            		                 
            	
            	
            	case IntroducerColumn.Gender:
            		return this.Gender.Value.CompareTo(rhs.Gender.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<IntroducerKey> Members
		
		// member variable for the EntityId property
		private IntroducerKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual IntroducerKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new IntroducerKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Introducer")
					.Append("|").Append( this.ID.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{13}{12}- ID: {0}{12}- Name: {1}{12}- Country: {2}{12}- City: {3}{12}- BirthDate: {4}{12}- Position: {5}{12}- IsAlive: {6}{12}- Mobile: {7}{12}- Email: {8}{12}- Website: {9}{12}- Book_ID: {10}{12}- Gender: {11}{12}{14}", 
				this.ID,
				this.Name,
				(this.Country == null) ? string.Empty : this.Country.ToString(),
				(this.City == null) ? string.Empty : this.City.ToString(),
				(this.BirthDate == null) ? string.Empty : this.BirthDate.ToString(),
				(this.Position == null) ? string.Empty : this.Position.ToString(),
				(this.IsAlive == null) ? string.Empty : this.IsAlive.ToString(),
				(this.Mobile == null) ? string.Empty : this.Mobile.ToString(),
				(this.Email == null) ? string.Empty : this.Email.ToString(),
				(this.Website == null) ? string.Empty : this.Website.ToString(),
				this.Book_ID,
				(this.Gender == null) ? string.Empty : this.Gender.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'Introducer' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class IntroducerEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Introducer"</remarks>
		public System.Int32 ID;
			
		#endregion
		
		#region Non Primary key(s)
		
		/// <summary>
		/// Name : 
		/// </summary>
		public System.String Name = string.Empty;
		
		/// <summary>
		/// Country : 
		/// </summary>
		public System.String Country = null;
		
		/// <summary>
		/// City : 
		/// </summary>
		public System.String City = null;
		
		/// <summary>
		/// BirthDate : 
		/// </summary>
		public System.DateTime? BirthDate = null;
		
		/// <summary>
		/// Position : 
		/// </summary>
		public System.String Position = null;
		
		/// <summary>
		/// IsAlive : 
		/// </summary>
		public System.String IsAlive = null;
		
		/// <summary>
		/// Mobile : 
		/// </summary>
		public System.String Mobile = null;
		
		/// <summary>
		/// Email : 
		/// </summary>
		public System.String Email = null;
		
		/// <summary>
		/// Website : 
		/// </summary>
		public System.String Website = null;
		
		/// <summary>
		/// Book_ID : 
		/// </summary>
		public System.Int32 Book_ID = (int)0;
		
		/// <summary>
		/// Gender : 
		/// </summary>
		public System.Boolean? Gender = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
        
		#endregion Variable Declarations

		#region Data Properties

		#region BookCollection
		
		private TList<Book> _bookIntroducer_ID;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bookIntroducer_ID
		/// </summary>
		
		public TList<Book> BookCollection
		{
			get
			{
				if (_bookIntroducer_ID == null)
				{
				_bookIntroducer_ID = new TList<Book>();
				}
	
				return _bookIntroducer_ID;
			}
			set { _bookIntroducer_ID = value; }
		}
		
		#endregion

		#endregion Data Properties
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			IntroducerEntityData _tmp = new IntroducerEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Name = this.Name;
			_tmp.Country = this.Country;
			_tmp.City = this.City;
			_tmp.BirthDate = this.BirthDate;
			_tmp.Position = this.Position;
			_tmp.IsAlive = this.IsAlive;
			_tmp.Mobile = this.Mobile;
			_tmp.Email = this.Email;
			_tmp.Website = this.Website;
			_tmp.Book_ID = this.Book_ID;
			_tmp.Gender = this.Gender;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._bookIntroducer_ID != null)
				_tmp.BookCollection = (TList<Book>) MakeCopyOf(this.BookCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			IntroducerEntityData _tmp = new IntroducerEntityData();
						
			_tmp.ID = this.ID;
			
			_tmp.Name = this.Name;
			_tmp.Country = this.Country;
			_tmp.City = this.City;
			_tmp.BirthDate = this.BirthDate;
			_tmp.Position = this.Position;
			_tmp.IsAlive = this.IsAlive;
			_tmp.Mobile = this.Mobile;
			_tmp.Email = this.Email;
			_tmp.Website = this.Website;
			_tmp.Book_ID = this.Book_ID;
			_tmp.Gender = this.Gender;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.BookCollection = (TList<Book>) MakeCopyOf(this.BookCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct

		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="IntroducerColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(IntroducerColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="IntroducerColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(IntroducerColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="IntroducerColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(IntroducerColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
                EntityManager.StopTracking(entityTrackingKey);
                
			if (!SuppressEntityEvents)
			{
				IntroducerEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new IntroducerEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="IntroducerColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(IntroducerColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				IntroducerEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new IntroducerEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region IntroducerEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Introducer"/> object.
	/// </remarks>
	public class IntroducerEventArgs : System.EventArgs
	{
		private IntroducerColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the IntroducerEventArgs class.
		///</summary>
		public IntroducerEventArgs(IntroducerColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the IntroducerEventArgs class.
		///</summary>
		public IntroducerEventArgs(IntroducerColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The IntroducerColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="IntroducerColumn" />
		public IntroducerColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Introducer related events.
	///</summary>
	public delegate void IntroducerEventHandler(object sender, IntroducerEventArgs e);
	
	#region IntroducerComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class IntroducerComparer : System.Collections.Generic.IComparer<Introducer>
	{
		IntroducerColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:IntroducerComparer"/> class.
        /// </summary>
		public IntroducerComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:IntroducerComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public IntroducerComparer(IntroducerColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <see cref="Introducer"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <see cref="Introducer"/> to compare.</param>
        /// <param name="b">The second <c>Introducer</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Introducer a, Introducer b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Introducer entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Introducer a, Introducer b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public IntroducerColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region IntroducerKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Introducer"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class IntroducerKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the IntroducerKey class.
		/// </summary>
		public IntroducerKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the IntroducerKey class.
		/// </summary>
		public IntroducerKey(IntroducerBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ID = entity.ID;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the IntroducerKey class.
		/// </summary>
		public IntroducerKey(System.Int32 _iD)
		{
			#region Init Properties

			this.ID = _iD;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private IntroducerBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public IntroducerBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ID property
		private System.Int32 _iD;
		
		/// <summary>
		/// Gets or sets the ID property.
		/// </summary>
		public System.Int32 ID
		{
			get { return _iD; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ID = value;
				
				_iD = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ID = ( values["ID"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ID"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ID", ID);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ID: {0}{1}",
								ID,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region IntroducerColumn Enum
	
	/// <summary>
	/// Enumerate the Introducer columns.
	/// </summary>
	[Serializable]
	public enum IntroducerColumn : int
	{
		/// <summary>
		/// ID : 
		/// </summary>
		[EnumTextValue("ID")]
		[ColumnEnum("ID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ID = 1,
		/// <summary>
		/// Name : 
		/// </summary>
		[EnumTextValue("Name")]
		[ColumnEnum("Name", typeof(System.String), System.Data.DbType.String, false, false, false, 50)]
		Name = 2,
		/// <summary>
		/// Country : 
		/// </summary>
		[EnumTextValue("Country")]
		[ColumnEnum("Country", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Country = 3,
		/// <summary>
		/// City : 
		/// </summary>
		[EnumTextValue("City")]
		[ColumnEnum("City", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		City = 4,
		/// <summary>
		/// BirthDate : 
		/// </summary>
		[EnumTextValue("Birth Date")]
		[ColumnEnum("BirthDate", typeof(System.DateTime), System.Data.DbType.Date, false, false, true)]
		BirthDate = 5,
		/// <summary>
		/// Position : 
		/// </summary>
		[EnumTextValue("Position")]
		[ColumnEnum("Position", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Position = 6,
		/// <summary>
		/// IsAlive : 
		/// </summary>
		[EnumTextValue("Is Alive")]
		[ColumnEnum("IsAlive", typeof(System.String), System.Data.DbType.StringFixedLength, false, false, true, 10)]
		IsAlive = 7,
		/// <summary>
		/// Mobile : 
		/// </summary>
		[EnumTextValue("Mobile")]
		[ColumnEnum("Mobile", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Mobile = 8,
		/// <summary>
		/// Email : 
		/// </summary>
		[EnumTextValue("Email")]
		[ColumnEnum("Email", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Email = 9,
		/// <summary>
		/// Website : 
		/// </summary>
		[EnumTextValue("Website")]
		[ColumnEnum("Website", typeof(System.String), System.Data.DbType.String, false, false, true, 50)]
		Website = 10,
		/// <summary>
		/// Book_ID : 
		/// </summary>
		[EnumTextValue("BookID")]
		[ColumnEnum("Book_ID", typeof(System.Int32), System.Data.DbType.Int32, false, false, false)]
		Book_ID = 11,
		/// <summary>
		/// Gender : 
		/// </summary>
		[EnumTextValue("Gender")]
		[ColumnEnum("Gender", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Gender = 12
	}//End enum

	#endregion IntroducerColumn Enum

} // end namespace
