using System;
using System.ComponentModel;

namespace Library.BLL
{
	/// <summary>
	///		The data structure representation of the 'Publisher' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IPublisher 
	{
		/// <summary>			
		/// ID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "Publisher"</remarks>
		System.Int32 ID { get; set; }
				
		
		
		/// <summary>
		/// Name : 
		/// </summary>
		System.String  Name  { get; set; }
		
		/// <summary>
		/// Mobile : 
		/// </summary>
		System.String  Mobile  { get; set; }
		
		/// <summary>
		/// Email : 
		/// </summary>
		System.String  Email  { get; set; }
		
		/// <summary>
		/// Website : 
		/// </summary>
		System.String  Website  { get; set; }
		
		/// <summary>
		/// FounedOn : 
		/// </summary>
		System.DateTime?  FounedOn  { get; set; }
		
		/// <summary>
		/// Country : 
		/// </summary>
		System.String  Country  { get; set; }
		
		/// <summary>
		/// City : 
		/// </summary>
		System.String  City  { get; set; }
		
		/// <summary>
		/// Address : 
		/// </summary>
		System.String  Address  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _bookPublisher_ID
		/// </summary>	
		TList<Book> BookCollection {  get;  set;}	

		#endregion Data Properties

	}
}


